---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: BHOS-NVIDIA
description: BlueHatOS w/ NVIDIA support
base-image: ghcr.io/ublue-os/kinoite-nvidia
image-version: latest

modules:
  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (System)"
      install:
        - app.polychromatic.controller
        - com.github.Matoking.protontricks
        - com.rustdesk.RustDesk
        - com.steamgriddb.SGDBoop
        - com.stremio.Stremio
        - com.visualstudio.code
        - md.obsidian.Obsidian
        - net.davidotek.pupgui2
        - org.audacityteam.Audacity
        - org.darktable.Darktable
        - org.gimp.GIMP
        - org.inkscape.Inkscape
        - org.kde.digikam
        - org.kde.gwenview
        - org.kde.kcalc
        - org.kde.kdenlive
        - org.kde.krita
        - org.kde.okular
        - org.kde.skanpage
        - org.onlyoffice.desktopeditors

  - type: rpm-ostree
    repos:
      - https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
    keys:
      - https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
    optfix:
      - brave.com
    install:
      - brave-browser
      - fastfetch
      - gamescope
      - kmod-openrazer
      - plasma-workspace-x11
      - steam
      - unrar
      - wine
    remove:
      - firefox
      - firefox-langpacks
  
  - type: signing
